DOOR = 'green'
GRILL = 'light blue'
PLAYER = 'red'
GOAL = 'yellow'
PORTAL1 = 'orange'
PORTAL2 = 'dodger blue'
CUBE = 'black'
BUTTON = 'red'
BUTTON_ACTIVE = 'dark red'
TRIGGER = 'blue'
WALL = 'black'

GRID = 'gray'
